#required= module_name, class_Name
DATASET:
  module_name: 'src.dataloader.Exampledataset'
  class_name: 'ExampleDataset'
  args:
    default:
      dataset_folder: './exampleDataset'
    training:
      dataset_folder: './exampleDataset'
    validation:
      dataset_folder: './exampleDataset'
    testing:
      dataset_folder: './exampleDataset'

