#required= module_name, class_Name
DATASET:
  module_name: 'src.dataloader.Exampledataset'
  class_name: 'ExampleDataset'
  args:
    default:
      required_input: ['IMAGE', 'GT']
      transforms: ['ToTensor']
      dataset_folder: './exampleDataset'
    training:
      required_input: ['IMAGE', 'GT']
      transforms: ['ToTensor']
      dataset_folder: './exampleDataset'
    validation:
      required_input: ['IMAGE', 'GT']
      transforms: ['ToTensor']
      dataset_folder: './exampleDataset'
    testing:
      required_input: ['IMAGE', 'GT']
      transforms: ['ToTensor']
      dataset_folder: './exampleDataset'