TRAINER:
  device: cuda # *
  gpu_ids: [0] # *

DATASET:
  module_name: ''
  class_name: ''
  args:
    training:
      dataset_folder: '/media/cvip/repo/dataset/dvs/'
    validation:
      dataset_folder: '/media/cvip/repo/dataset/dvs/'
    testing:
      dataset_folder: '/media/cvip/repo/dataset/dvs/'



DATA_LOADER:
  default_transform_module: 'framework.dataloader.Transform'
  required_loader: ['training', 'validation', 'testing']
  args:
    version: 1
    training:
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3
    validation:
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3
    testing:
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3

VISUALIZER:
  request_mailspot_path: ''
  answer_mailspot_path: ''

SYSTEM:
  SEED: 42
  REPRODUCIBILITY: False

  LOGGER:
    version: 1
    disable_existing_loggers: true

    formatters:
      standard:
        format: "[%(asctime)s]/[%(name)s]/[%(levelname)s]: %(message)s"
      error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
      training:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
      testing:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

    handlers:
      training_log_handler:
        class: logging.FileHandler
        level: INFO
        formatter: training
        filename: "./training_info.log"

      training_log_console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: training
        stream: ext://sys.stdout

      testing_log_handler:
        class: logging.FileHandler
        level: INFO
        formatter: training
        filename: "./testing_info.log"

      testing_log_console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: training
        stream: ext://sys.stdout

      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

      info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /tmp/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /tmp/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /tmp/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /tmp/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /tmp/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    root:
      level: NOTSET
      handlers: [console]
      propagate: yes

    loggers:
      DEFAULT:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propagate: no

      DEBUG_MODE:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propagate: yes

      TRAINING_MODE:
        level: INFO
        handlers: [training_log_handler, training_log_console_handler]
        propagate: no

      TESTING_MODE:
        level: INFO
        handlers: [testing_log_handler, testing_log_console_handler]
        propagate: no


LDI:
  type: 'stereo'
  size: [540, 960]
  rendering_size: [540, 960]
  camera:
    camera_module: 'dataloader.sceneflow_dataloader'
    camera_class: 'sceneflow_cameras'
    scale: 1
  virtual_camera:
    T: null
    R: null

# ALGORITHM
disp_threshold: 2.5
camera_path: [[0.02,0, 0,0],[0.02,0.02,0],[0,0.02,0],[0,0,0]]
#camera_path: [[0,0,0.02],[0,0, -0.02],[0,0,0],[0,0,0]]
