App:
  NAME: 'ExampleNet'
  EXPERIMENT_NAME: 'scenario1'
  device: cuda # *
  gpu_ids: [0] # *
  parallel: 'data' #  model
  save_dir: 'resource/output/'
  mode: 'new' # new, finetuning, resume

MODEL_CONTROLLER:
  COMMAND_CONTROLLER:
    command_path: 'resource/ipc/default_command.yaml'

  MODEL_STATE_CONTROLLER: {}
  OPTIMIZER:
    # ADAM
    optimizer:
      optimizer_module: 'torch.optim'
      optimizer_class: 'Adam'
      optimizer_args:
        lr: 1e-4
        weight_decay: 0
        betas: [0.9, 0.999]
        eps: 1e-8
    scheduler:
      scheduler_module: 'torch.optim.lr_scheduler'
      scheduler_class: 'MultiStepLR'
      scheduler_args:
        milestones: [200]
        gamma: 0.5
  LOSSES: {}

DATA_LOADER:
  required_input: []
  default_transform_module: 'framework.dataloader.Transform'
  default_transforms: []
  required_loader:
    # NAME, args
    default:
      config:
        reload: true
        mode: eval
        obj_epoch: 1
      transforms: [ToTensor]
      loader_args:
        batch_size: 1
        shuffle: False
        pin_memory: True
        num_workers: 3
    training:
      dataset: 'resource/configs/dataset/Example.yaml'
      config:
        reload: false
        mode: train
        obj_epoch: 10
      transforms: [ToTensor]
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3
    validation:
      dataset: 'resource/configs/dataset/Example.yaml'
      transforms: [ToTensor]
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3
    testing:
      dataset: 'resource/configs/dataset/Example.yaml'
      transforms: [ToTensor]
      loader_args:
        batch_size: 1
        shuffle: True
        pin_memory: True
        num_workers: 3

SYSTEM:
  SEED: 42
  REPRODUCIBILITY: False

  LOGGER:
    version: 1
    disable_existing_loggers: true

    formatters:
      standard:
        format: "[%(asctime)s]/[%(name)s]/[%(levelname)s]: %(message)s"
      error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
      training:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
      testing:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

    handlers:
      training_log_handler:
        class: logging.FileHandler
        level: INFO
        formatter: training
        filename: "./training_info.log"

      training_log_console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: training
        stream: ext://sys.stdout

      testing_log_handler:
        class: logging.FileHandler
        level: INFO
        formatter: training
        filename: "./testing_info.log"

      testing_log_console_handler:
        class: logging.StreamHandler
        level: INFO
        formatter: training
        stream: ext://sys.stdout

      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

      info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /tmp/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /tmp/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /tmp/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /tmp/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

      warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: /tmp/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    root:
      level: NOTSET
      handlers: [console]
      propagate: yes

    loggers:
      DEFAULT:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propagate: no

      DEBUG_MODE:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
        propagate: yes

      TRAINING_MODE:
        level: INFO
        handlers: [training_log_handler, training_log_console_handler]
        propagate: no

      TESTING_MODE:
        level: INFO
        handlers: [testing_log_handler, testing_log_console_handler]
        propagate: no