DATA_LOADER:
  required_loader:
    training:
      dataset: 'resource/configs/dataset/Example.yaml'
      loader_args:
        batch_size: 2
#      dataset_args: {}
    validation:
      dataset: 'resource/configs/dataset/Example.yaml'
    testing:
      dataset: 'resource/configs/dataset/Example.yaml'
      transforms: [ToTensor:IMAGE-GT,]
#      required_input: ['XX']
  args:
    output_required: []
    version: 1

